name: build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install distribution packages
        run: |
          sudo apt update
          sudo apt install libgtk-4-dev libgirepository1.0-dev python-gi-dev libsoup-3.0-dev meson
          sudo apt install desktop-file-utils appstream-util

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 markdown markupsafe pygments toml typogrify
          pip install pipenv
          pipenv install --dev

      - name: Cache libshumate
        id: cache-libshumate
        uses: actions/cache@v3
        with:
          path: libshumate
          key: ${{ runner.os }}-libshumate-1.0.0

      - name: Clone libshumate
        if: steps.cache-libshumate.outputs.cache-hit != 'true'
        run: |
          git clone --branch 1.0.0 https://gitlab.gnome.org/GNOME/libshumate.git
          cd libshumate
          meson setup build
          meson compile -C build

      - name: Install libshumate
        run: |
          cd libshumate
          sudo meson install -C build

      - name: Lint with flake8 & mypy
        run: |
          pipenv run flake8 --ignore E402,D100,D104,D107 --show-source pygpxviewer/
          pipenv run mypy --strict-equality --ignore-missing-imports --disallow-incomplete-defs pygpxviewer

      - name: Build with meson
        run: |
          pipenv run meson setup build
          pipenv run meson compile -C build
          pipenv run meson test -C build
