name: docs

on: [ push ]

jobs:
  docs:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install distribution packages
        run: |
          sudo apt update

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source/ docs/build/html

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
