# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: master

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo add-apt-repository universe
          ls /var/lib/apt/lists/
          sudo apt update
          grep ^Package /var/lib/apt/lists/azure.archive.ubuntu.com_ubuntu_dists_jammy_universe_binary-amd64_Packages | awk '{print $2}' | sort -u
          sudo apt install libgtk-4-dev libgirepository1.0-dev python-gi-dev desktop-file-utils libshumate-1.0-1
          pip install pipenv
          pipenv install --dev

      - name: Lint with isort & flake8
        run: |
          pipenv run isort pygoxviewer
          pipenv run flake8 pygpxviewer --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 pygpxviewer --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build with meson
        run: |
          pipenv run meson build
          pipenv run ninja -C build